ALTER TABLE "Order" ADD COLUMN "deliveryArea" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Order" ADD COLUMN "deliveryCharge" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "costingAmount" DECIMAL NOT NULL DEFAULT 0;
