-- AlterTable
ALTER TABLE "Order" ADD COLUMN "paymentMethod" TEXT NOT NULL DEFAULT 'CASH';
ALTER TABLE "Order" ADD COLUMN "paidAmount" DECIMAL NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "changeDue" DECIMAL NOT NULL DEFAULT 0;
